<?php

module_load_include('inc', 'nnels_content_cafe', 'nnels_content_cafe.class');
module_load_include('inc', 'nnels_content_cafe', 'nnels_content_cafe');

/**
 * Implements hook_permission().
 */
function nnels_content_cafe_permission() {
  return array(
    'administer nnels content cafe' => array(
      'title'       => t('Administer NNELS content cafe'),
      'description' => t('Perform administration tasks for NNELS content cafe.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function nnels_content_cafe_menu() {
  $items = array();

  // Settings Pages
  $items['admin/config/nnels'] = array(
    'title'            => 'NNELS Configuration',
    'description'      => 'Manage configuration for NNELS Custom Modules.',
    'position'         => 'right',
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
    'weight'           => 30,
  );
  $items['admin/config/nnels/settings'] = array(
    'title'            => 'Content Cafe API Settings',
    'description'      => 'API Settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_settings_form'),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['admin/config/nnels/tests'] = array(
    'title'            => 'Content Cafe API Test Calls',
    'description'      => 'Test Content Cafe API Calls',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_test_form'),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['admin/config/nnels/repository_items'] = array(
    'title'            => 'Repository Items with API Data',
    'description'      => 'A list of repository items that have content cafe API data attached.',
    'page callback'    => 'nnels_content_cafe_repository_item_list',
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );

  // Node Pages
  $items['node/%/content_cafe'] = array(
    'title'            => 'Content Cafe',
    'description'      => 'Data from the Content Cafe API',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_overview_form', 1),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 50,
  );
  $items['node/%/content_cafe/annotation/%/edit'] = array(
    'title'            => 'Edit Annotation',
    'description'      => 'Edit a specic annotation for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_annotation_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['node/%/content_cafe/biography/%/edit'] = array(
    'title'            => 'Edit Biography',
    'description'      => 'Edit a specic biography for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_biography_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['node/%/content_cafe/excerpt/%/edit'] = array(
    'title'            => 'Edit Excerpt',
    'description'      => 'Edit a specic excerpt for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_excerpt_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['node/%/content_cafe/flap/%/edit'] = array(
    'title'            => 'Edit Flap',
    'description'      => 'Edit a specic flap for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_flap_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['node/%/content_cafe/jacket/%/edit'] = array(
    'title'            => 'Edit Jacket',
    'description'      => 'Edit a specic jacket for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_jacket_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );
  $items['node/%/content_cafe/toc/%/edit'] = array(
    'title'            => 'Edit TOC',
    'description'      => 'Edit a specic toc for a repository item.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nnels_content_cafe_toc_edit_form', 1, 4),
    'access arguments' => array('administer nnels content cafe'),
    'file'             => 'nnels_content_cafe.admin.inc',
    'file path'        => drupal_get_path('module', 'nnels_content_cafe'),
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function nnels_content_cafe_admin_paths() {
  $paths = array(
    'node/*/content_cafe'   => TRUE,
    'node/*/content_cafe/*' => TRUE,
  );

  return $paths;
}

/**
 * Implements hook_views_api().
 */
function nnels_content_cafe_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_post_execute().
 */
function nnels_content_cafe_views_post_execute(&$view) {

  // Selected Annotation field.
  if (isset($view->field['content_cafe_selected_annotation'])) {

    // Get a list of nodes so the data can be selected in a bulk fashion.
    $nids = array();
    foreach ($view->result as $result) {
      $nids[] = $result->nid;
    }
    $annotations = nnels_content_cafe_select_multiple_content_cafe_annotation_rows_by_nids($nids);
    
    // Update the results with the data.
    foreach ($view->result as $result) {
      if (isset($annotations[$result->nid])) {
        foreach ($annotations[$result->nid] as $annotation) {
          if ($annotation->selected) {
            $result->content_cafe_selected_annotation = $annotation->annotation;
          }
        }
      }
      else {
        $result->content_cafe_selected_annotation = NULL;
      }
    }
  }
}